################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../Dsp/Src/FilteringFunctions/arm_conv_f32.c \
../Dsp/Src/FilteringFunctions/arm_conv_fast_opt_q15.c \
../Dsp/Src/FilteringFunctions/arm_conv_fast_q15.c \
../Dsp/Src/FilteringFunctions/arm_conv_fast_q31.c \
../Dsp/Src/FilteringFunctions/arm_conv_opt_q15.c \
../Dsp/Src/FilteringFunctions/arm_conv_opt_q7.c \
../Dsp/Src/FilteringFunctions/arm_conv_partial_f32.c \
../Dsp/Src/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q15.c \
../Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q31.c \
../Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q15.c \
../Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q7.c \
../Dsp/Src/FilteringFunctions/arm_conv_partial_q15.c \
../Dsp/Src/FilteringFunctions/arm_conv_partial_q31.c \
../Dsp/Src/FilteringFunctions/arm_conv_partial_q7.c \
../Dsp/Src/FilteringFunctions/arm_conv_q15.c \
../Dsp/Src/FilteringFunctions/arm_conv_q31.c \
../Dsp/Src/FilteringFunctions/arm_conv_q7.c \
../Dsp/Src/FilteringFunctions/arm_correlate_f32.c \
../Dsp/Src/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../Dsp/Src/FilteringFunctions/arm_correlate_fast_q15.c \
../Dsp/Src/FilteringFunctions/arm_correlate_fast_q31.c \
../Dsp/Src/FilteringFunctions/arm_correlate_opt_q15.c \
../Dsp/Src/FilteringFunctions/arm_correlate_opt_q7.c \
../Dsp/Src/FilteringFunctions/arm_correlate_q15.c \
../Dsp/Src/FilteringFunctions/arm_correlate_q31.c \
../Dsp/Src/FilteringFunctions/arm_correlate_q7.c \
../Dsp/Src/FilteringFunctions/arm_fir_decimate_f32.c \
../Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../Dsp/Src/FilteringFunctions/arm_fir_decimate_init_f32.c \
../Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q15.c \
../Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q31.c \
../Dsp/Src/FilteringFunctions/arm_fir_decimate_q15.c \
../Dsp/Src/FilteringFunctions/arm_fir_decimate_q31.c \
../Dsp/Src/FilteringFunctions/arm_fir_f32.c \
../Dsp/Src/FilteringFunctions/arm_fir_fast_q15.c \
../Dsp/Src/FilteringFunctions/arm_fir_fast_q31.c \
../Dsp/Src/FilteringFunctions/arm_fir_init_f32.c \
../Dsp/Src/FilteringFunctions/arm_fir_init_q15.c \
../Dsp/Src/FilteringFunctions/arm_fir_init_q31.c \
../Dsp/Src/FilteringFunctions/arm_fir_init_q7.c \
../Dsp/Src/FilteringFunctions/arm_fir_interpolate_f32.c \
../Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../Dsp/Src/FilteringFunctions/arm_fir_interpolate_q15.c \
../Dsp/Src/FilteringFunctions/arm_fir_interpolate_q31.c \
../Dsp/Src/FilteringFunctions/arm_fir_lattice_f32.c \
../Dsp/Src/FilteringFunctions/arm_fir_lattice_init_f32.c \
../Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q15.c \
../Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q31.c \
../Dsp/Src/FilteringFunctions/arm_fir_lattice_q15.c \
../Dsp/Src/FilteringFunctions/arm_fir_lattice_q31.c \
../Dsp/Src/FilteringFunctions/arm_fir_q15.c \
../Dsp/Src/FilteringFunctions/arm_fir_q31.c \
../Dsp/Src/FilteringFunctions/arm_fir_q7.c \
../Dsp/Src/FilteringFunctions/arm_fir_sparse_f32.c \
../Dsp/Src/FilteringFunctions/arm_fir_sparse_init_f32.c \
../Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q15.c \
../Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q31.c \
../Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q7.c \
../Dsp/Src/FilteringFunctions/arm_fir_sparse_q15.c \
../Dsp/Src/FilteringFunctions/arm_fir_sparse_q31.c \
../Dsp/Src/FilteringFunctions/arm_fir_sparse_q7.c \
../Dsp/Src/FilteringFunctions/arm_iir_lattice_f32.c \
../Dsp/Src/FilteringFunctions/arm_iir_lattice_init_f32.c \
../Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q15.c \
../Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q31.c \
../Dsp/Src/FilteringFunctions/arm_iir_lattice_q15.c \
../Dsp/Src/FilteringFunctions/arm_iir_lattice_q31.c \
../Dsp/Src/FilteringFunctions/arm_lms_f32.c \
../Dsp/Src/FilteringFunctions/arm_lms_init_f32.c \
../Dsp/Src/FilteringFunctions/arm_lms_init_q15.c \
../Dsp/Src/FilteringFunctions/arm_lms_init_q31.c \
../Dsp/Src/FilteringFunctions/arm_lms_norm_f32.c \
../Dsp/Src/FilteringFunctions/arm_lms_norm_init_f32.c \
../Dsp/Src/FilteringFunctions/arm_lms_norm_init_q15.c \
../Dsp/Src/FilteringFunctions/arm_lms_norm_init_q31.c \
../Dsp/Src/FilteringFunctions/arm_lms_norm_q15.c \
../Dsp/Src/FilteringFunctions/arm_lms_norm_q31.c \
../Dsp/Src/FilteringFunctions/arm_lms_q15.c \
../Dsp/Src/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./Dsp/Src/FilteringFunctions/arm_conv_f32.o \
./Dsp/Src/FilteringFunctions/arm_conv_fast_opt_q15.o \
./Dsp/Src/FilteringFunctions/arm_conv_fast_q15.o \
./Dsp/Src/FilteringFunctions/arm_conv_fast_q31.o \
./Dsp/Src/FilteringFunctions/arm_conv_opt_q15.o \
./Dsp/Src/FilteringFunctions/arm_conv_opt_q7.o \
./Dsp/Src/FilteringFunctions/arm_conv_partial_f32.o \
./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q15.o \
./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q31.o \
./Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q15.o \
./Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q7.o \
./Dsp/Src/FilteringFunctions/arm_conv_partial_q15.o \
./Dsp/Src/FilteringFunctions/arm_conv_partial_q31.o \
./Dsp/Src/FilteringFunctions/arm_conv_partial_q7.o \
./Dsp/Src/FilteringFunctions/arm_conv_q15.o \
./Dsp/Src/FilteringFunctions/arm_conv_q31.o \
./Dsp/Src/FilteringFunctions/arm_conv_q7.o \
./Dsp/Src/FilteringFunctions/arm_correlate_f32.o \
./Dsp/Src/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./Dsp/Src/FilteringFunctions/arm_correlate_fast_q15.o \
./Dsp/Src/FilteringFunctions/arm_correlate_fast_q31.o \
./Dsp/Src/FilteringFunctions/arm_correlate_opt_q15.o \
./Dsp/Src/FilteringFunctions/arm_correlate_opt_q7.o \
./Dsp/Src/FilteringFunctions/arm_correlate_q15.o \
./Dsp/Src/FilteringFunctions/arm_correlate_q31.o \
./Dsp/Src/FilteringFunctions/arm_correlate_q7.o \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_f32.o \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_f32.o \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q15.o \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q31.o \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_q15.o \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_q31.o \
./Dsp/Src/FilteringFunctions/arm_fir_f32.o \
./Dsp/Src/FilteringFunctions/arm_fir_fast_q15.o \
./Dsp/Src/FilteringFunctions/arm_fir_fast_q31.o \
./Dsp/Src/FilteringFunctions/arm_fir_init_f32.o \
./Dsp/Src/FilteringFunctions/arm_fir_init_q15.o \
./Dsp/Src/FilteringFunctions/arm_fir_init_q31.o \
./Dsp/Src/FilteringFunctions/arm_fir_init_q7.o \
./Dsp/Src/FilteringFunctions/arm_fir_interpolate_f32.o \
./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./Dsp/Src/FilteringFunctions/arm_fir_interpolate_q15.o \
./Dsp/Src/FilteringFunctions/arm_fir_interpolate_q31.o \
./Dsp/Src/FilteringFunctions/arm_fir_lattice_f32.o \
./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_f32.o \
./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q15.o \
./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q31.o \
./Dsp/Src/FilteringFunctions/arm_fir_lattice_q15.o \
./Dsp/Src/FilteringFunctions/arm_fir_lattice_q31.o \
./Dsp/Src/FilteringFunctions/arm_fir_q15.o \
./Dsp/Src/FilteringFunctions/arm_fir_q31.o \
./Dsp/Src/FilteringFunctions/arm_fir_q7.o \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_f32.o \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_f32.o \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q15.o \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q31.o \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q7.o \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_q15.o \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_q31.o \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_q7.o \
./Dsp/Src/FilteringFunctions/arm_iir_lattice_f32.o \
./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_f32.o \
./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q15.o \
./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q31.o \
./Dsp/Src/FilteringFunctions/arm_iir_lattice_q15.o \
./Dsp/Src/FilteringFunctions/arm_iir_lattice_q31.o \
./Dsp/Src/FilteringFunctions/arm_lms_f32.o \
./Dsp/Src/FilteringFunctions/arm_lms_init_f32.o \
./Dsp/Src/FilteringFunctions/arm_lms_init_q15.o \
./Dsp/Src/FilteringFunctions/arm_lms_init_q31.o \
./Dsp/Src/FilteringFunctions/arm_lms_norm_f32.o \
./Dsp/Src/FilteringFunctions/arm_lms_norm_init_f32.o \
./Dsp/Src/FilteringFunctions/arm_lms_norm_init_q15.o \
./Dsp/Src/FilteringFunctions/arm_lms_norm_init_q31.o \
./Dsp/Src/FilteringFunctions/arm_lms_norm_q15.o \
./Dsp/Src/FilteringFunctions/arm_lms_norm_q31.o \
./Dsp/Src/FilteringFunctions/arm_lms_q15.o \
./Dsp/Src/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./Dsp/Src/FilteringFunctions/arm_conv_f32.d \
./Dsp/Src/FilteringFunctions/arm_conv_fast_opt_q15.d \
./Dsp/Src/FilteringFunctions/arm_conv_fast_q15.d \
./Dsp/Src/FilteringFunctions/arm_conv_fast_q31.d \
./Dsp/Src/FilteringFunctions/arm_conv_opt_q15.d \
./Dsp/Src/FilteringFunctions/arm_conv_opt_q7.d \
./Dsp/Src/FilteringFunctions/arm_conv_partial_f32.d \
./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q15.d \
./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q31.d \
./Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q15.d \
./Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q7.d \
./Dsp/Src/FilteringFunctions/arm_conv_partial_q15.d \
./Dsp/Src/FilteringFunctions/arm_conv_partial_q31.d \
./Dsp/Src/FilteringFunctions/arm_conv_partial_q7.d \
./Dsp/Src/FilteringFunctions/arm_conv_q15.d \
./Dsp/Src/FilteringFunctions/arm_conv_q31.d \
./Dsp/Src/FilteringFunctions/arm_conv_q7.d \
./Dsp/Src/FilteringFunctions/arm_correlate_f32.d \
./Dsp/Src/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./Dsp/Src/FilteringFunctions/arm_correlate_fast_q15.d \
./Dsp/Src/FilteringFunctions/arm_correlate_fast_q31.d \
./Dsp/Src/FilteringFunctions/arm_correlate_opt_q15.d \
./Dsp/Src/FilteringFunctions/arm_correlate_opt_q7.d \
./Dsp/Src/FilteringFunctions/arm_correlate_q15.d \
./Dsp/Src/FilteringFunctions/arm_correlate_q31.d \
./Dsp/Src/FilteringFunctions/arm_correlate_q7.d \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_f32.d \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_f32.d \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q15.d \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q31.d \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_q15.d \
./Dsp/Src/FilteringFunctions/arm_fir_decimate_q31.d \
./Dsp/Src/FilteringFunctions/arm_fir_f32.d \
./Dsp/Src/FilteringFunctions/arm_fir_fast_q15.d \
./Dsp/Src/FilteringFunctions/arm_fir_fast_q31.d \
./Dsp/Src/FilteringFunctions/arm_fir_init_f32.d \
./Dsp/Src/FilteringFunctions/arm_fir_init_q15.d \
./Dsp/Src/FilteringFunctions/arm_fir_init_q31.d \
./Dsp/Src/FilteringFunctions/arm_fir_init_q7.d \
./Dsp/Src/FilteringFunctions/arm_fir_interpolate_f32.d \
./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./Dsp/Src/FilteringFunctions/arm_fir_interpolate_q15.d \
./Dsp/Src/FilteringFunctions/arm_fir_interpolate_q31.d \
./Dsp/Src/FilteringFunctions/arm_fir_lattice_f32.d \
./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_f32.d \
./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q15.d \
./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q31.d \
./Dsp/Src/FilteringFunctions/arm_fir_lattice_q15.d \
./Dsp/Src/FilteringFunctions/arm_fir_lattice_q31.d \
./Dsp/Src/FilteringFunctions/arm_fir_q15.d \
./Dsp/Src/FilteringFunctions/arm_fir_q31.d \
./Dsp/Src/FilteringFunctions/arm_fir_q7.d \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_f32.d \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_f32.d \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q15.d \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q31.d \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q7.d \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_q15.d \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_q31.d \
./Dsp/Src/FilteringFunctions/arm_fir_sparse_q7.d \
./Dsp/Src/FilteringFunctions/arm_iir_lattice_f32.d \
./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_f32.d \
./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q15.d \
./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q31.d \
./Dsp/Src/FilteringFunctions/arm_iir_lattice_q15.d \
./Dsp/Src/FilteringFunctions/arm_iir_lattice_q31.d \
./Dsp/Src/FilteringFunctions/arm_lms_f32.d \
./Dsp/Src/FilteringFunctions/arm_lms_init_f32.d \
./Dsp/Src/FilteringFunctions/arm_lms_init_q15.d \
./Dsp/Src/FilteringFunctions/arm_lms_init_q31.d \
./Dsp/Src/FilteringFunctions/arm_lms_norm_f32.d \
./Dsp/Src/FilteringFunctions/arm_lms_norm_init_f32.d \
./Dsp/Src/FilteringFunctions/arm_lms_norm_init_q15.d \
./Dsp/Src/FilteringFunctions/arm_lms_norm_init_q31.d \
./Dsp/Src/FilteringFunctions/arm_lms_norm_q15.d \
./Dsp/Src/FilteringFunctions/arm_lms_norm_q31.d \
./Dsp/Src/FilteringFunctions/arm_lms_q15.d \
./Dsp/Src/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Dsp/Src/FilteringFunctions/%.o Dsp/Src/FilteringFunctions/%.su Dsp/Src/FilteringFunctions/%.cyclo: ../Dsp/Src/FilteringFunctions/%.c Dsp/Src/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32H743xx -c -I"/home/daniel/Documents/workspace/FX-4CR/User/Inc" -I"/home/daniel/Documents/workspace/FX-4CR/Core/Inc" -I"/home/daniel/Documents/workspace/FX-4CR/Dsp/Inc" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Dsp-2f-Src-2f-FilteringFunctions

clean-Dsp-2f-Src-2f-FilteringFunctions:
	-$(RM) ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f64.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./Dsp/Src/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./Dsp/Src/FilteringFunctions/arm_conv_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_f32.d ./Dsp/Src/FilteringFunctions/arm_conv_f32.o ./Dsp/Src/FilteringFunctions/arm_conv_f32.su ./Dsp/Src/FilteringFunctions/arm_conv_fast_opt_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_fast_opt_q15.d ./Dsp/Src/FilteringFunctions/arm_conv_fast_opt_q15.o ./Dsp/Src/FilteringFunctions/arm_conv_fast_opt_q15.su ./Dsp/Src/FilteringFunctions/arm_conv_fast_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_fast_q15.d ./Dsp/Src/FilteringFunctions/arm_conv_fast_q15.o ./Dsp/Src/FilteringFunctions/arm_conv_fast_q15.su ./Dsp/Src/FilteringFunctions/arm_conv_fast_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_fast_q31.d ./Dsp/Src/FilteringFunctions/arm_conv_fast_q31.o ./Dsp/Src/FilteringFunctions/arm_conv_fast_q31.su ./Dsp/Src/FilteringFunctions/arm_conv_opt_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_opt_q15.d ./Dsp/Src/FilteringFunctions/arm_conv_opt_q15.o ./Dsp/Src/FilteringFunctions/arm_conv_opt_q15.su ./Dsp/Src/FilteringFunctions/arm_conv_opt_q7.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_opt_q7.d ./Dsp/Src/FilteringFunctions/arm_conv_opt_q7.o ./Dsp/Src/FilteringFunctions/arm_conv_opt_q7.su ./Dsp/Src/FilteringFunctions/arm_conv_partial_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_partial_f32.d ./Dsp/Src/FilteringFunctions/arm_conv_partial_f32.o ./Dsp/Src/FilteringFunctions/arm_conv_partial_f32.su ./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_opt_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q15.d ./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q15.o ./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q15.su
	-$(RM) ./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q31.d ./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q31.o ./Dsp/Src/FilteringFunctions/arm_conv_partial_fast_q31.su ./Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q15.d ./Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q15.o ./Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q15.su ./Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q7.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q7.d ./Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q7.o ./Dsp/Src/FilteringFunctions/arm_conv_partial_opt_q7.su ./Dsp/Src/FilteringFunctions/arm_conv_partial_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_partial_q15.d ./Dsp/Src/FilteringFunctions/arm_conv_partial_q15.o ./Dsp/Src/FilteringFunctions/arm_conv_partial_q15.su ./Dsp/Src/FilteringFunctions/arm_conv_partial_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_partial_q31.d ./Dsp/Src/FilteringFunctions/arm_conv_partial_q31.o ./Dsp/Src/FilteringFunctions/arm_conv_partial_q31.su ./Dsp/Src/FilteringFunctions/arm_conv_partial_q7.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_partial_q7.d ./Dsp/Src/FilteringFunctions/arm_conv_partial_q7.o ./Dsp/Src/FilteringFunctions/arm_conv_partial_q7.su ./Dsp/Src/FilteringFunctions/arm_conv_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_q15.d ./Dsp/Src/FilteringFunctions/arm_conv_q15.o ./Dsp/Src/FilteringFunctions/arm_conv_q15.su ./Dsp/Src/FilteringFunctions/arm_conv_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_q31.d ./Dsp/Src/FilteringFunctions/arm_conv_q31.o ./Dsp/Src/FilteringFunctions/arm_conv_q31.su ./Dsp/Src/FilteringFunctions/arm_conv_q7.cyclo ./Dsp/Src/FilteringFunctions/arm_conv_q7.d ./Dsp/Src/FilteringFunctions/arm_conv_q7.o ./Dsp/Src/FilteringFunctions/arm_conv_q7.su ./Dsp/Src/FilteringFunctions/arm_correlate_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_correlate_f32.d ./Dsp/Src/FilteringFunctions/arm_correlate_f32.o ./Dsp/Src/FilteringFunctions/arm_correlate_f32.su ./Dsp/Src/FilteringFunctions/arm_correlate_fast_opt_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_correlate_fast_opt_q15.d ./Dsp/Src/FilteringFunctions/arm_correlate_fast_opt_q15.o ./Dsp/Src/FilteringFunctions/arm_correlate_fast_opt_q15.su ./Dsp/Src/FilteringFunctions/arm_correlate_fast_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_correlate_fast_q15.d ./Dsp/Src/FilteringFunctions/arm_correlate_fast_q15.o ./Dsp/Src/FilteringFunctions/arm_correlate_fast_q15.su ./Dsp/Src/FilteringFunctions/arm_correlate_fast_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_correlate_fast_q31.d ./Dsp/Src/FilteringFunctions/arm_correlate_fast_q31.o ./Dsp/Src/FilteringFunctions/arm_correlate_fast_q31.su ./Dsp/Src/FilteringFunctions/arm_correlate_opt_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_correlate_opt_q15.d ./Dsp/Src/FilteringFunctions/arm_correlate_opt_q15.o ./Dsp/Src/FilteringFunctions/arm_correlate_opt_q15.su ./Dsp/Src/FilteringFunctions/arm_correlate_opt_q7.cyclo ./Dsp/Src/FilteringFunctions/arm_correlate_opt_q7.d ./Dsp/Src/FilteringFunctions/arm_correlate_opt_q7.o ./Dsp/Src/FilteringFunctions/arm_correlate_opt_q7.su ./Dsp/Src/FilteringFunctions/arm_correlate_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_correlate_q15.d ./Dsp/Src/FilteringFunctions/arm_correlate_q15.o ./Dsp/Src/FilteringFunctions/arm_correlate_q15.su ./Dsp/Src/FilteringFunctions/arm_correlate_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_correlate_q31.d ./Dsp/Src/FilteringFunctions/arm_correlate_q31.o ./Dsp/Src/FilteringFunctions/arm_correlate_q31.su ./Dsp/Src/FilteringFunctions/arm_correlate_q7.cyclo ./Dsp/Src/FilteringFunctions/arm_correlate_q7.d ./Dsp/Src/FilteringFunctions/arm_correlate_q7.o ./Dsp/Src/FilteringFunctions/arm_correlate_q7.su ./Dsp/Src/FilteringFunctions/arm_fir_decimate_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_decimate_f32.d ./Dsp/Src/FilteringFunctions/arm_fir_decimate_f32.o ./Dsp/Src/FilteringFunctions/arm_fir_decimate_f32.su ./Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q15.d ./Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q15.o ./Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q15.su ./Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q31.d ./Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q31.o ./Dsp/Src/FilteringFunctions/arm_fir_decimate_fast_q31.su ./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_f32.d ./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_f32.o ./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_f32.su ./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q15.d ./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q15.o ./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q15.su ./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q31.d ./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q31.o ./Dsp/Src/FilteringFunctions/arm_fir_decimate_init_q31.su ./Dsp/Src/FilteringFunctions/arm_fir_decimate_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_decimate_q15.d ./Dsp/Src/FilteringFunctions/arm_fir_decimate_q15.o ./Dsp/Src/FilteringFunctions/arm_fir_decimate_q15.su ./Dsp/Src/FilteringFunctions/arm_fir_decimate_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_decimate_q31.d ./Dsp/Src/FilteringFunctions/arm_fir_decimate_q31.o ./Dsp/Src/FilteringFunctions/arm_fir_decimate_q31.su ./Dsp/Src/FilteringFunctions/arm_fir_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_f32.d ./Dsp/Src/FilteringFunctions/arm_fir_f32.o ./Dsp/Src/FilteringFunctions/arm_fir_f32.su ./Dsp/Src/FilteringFunctions/arm_fir_fast_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_fast_q15.d ./Dsp/Src/FilteringFunctions/arm_fir_fast_q15.o ./Dsp/Src/FilteringFunctions/arm_fir_fast_q15.su
	-$(RM) ./Dsp/Src/FilteringFunctions/arm_fir_fast_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_fast_q31.d ./Dsp/Src/FilteringFunctions/arm_fir_fast_q31.o ./Dsp/Src/FilteringFunctions/arm_fir_fast_q31.su ./Dsp/Src/FilteringFunctions/arm_fir_init_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_init_f32.d ./Dsp/Src/FilteringFunctions/arm_fir_init_f32.o ./Dsp/Src/FilteringFunctions/arm_fir_init_f32.su ./Dsp/Src/FilteringFunctions/arm_fir_init_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_init_q15.d ./Dsp/Src/FilteringFunctions/arm_fir_init_q15.o ./Dsp/Src/FilteringFunctions/arm_fir_init_q15.su ./Dsp/Src/FilteringFunctions/arm_fir_init_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_init_q31.d ./Dsp/Src/FilteringFunctions/arm_fir_init_q31.o ./Dsp/Src/FilteringFunctions/arm_fir_init_q31.su ./Dsp/Src/FilteringFunctions/arm_fir_init_q7.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_init_q7.d ./Dsp/Src/FilteringFunctions/arm_fir_init_q7.o ./Dsp/Src/FilteringFunctions/arm_fir_init_q7.su ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_f32.d ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_f32.o ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_f32.su ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_f32.d ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_f32.o ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_f32.su ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q15.d ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q15.o ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q15.su ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q31.d ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q31.o ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_init_q31.su ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_q15.d ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_q15.o ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_q15.su ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_q31.d ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_q31.o ./Dsp/Src/FilteringFunctions/arm_fir_interpolate_q31.su ./Dsp/Src/FilteringFunctions/arm_fir_lattice_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_lattice_f32.d ./Dsp/Src/FilteringFunctions/arm_fir_lattice_f32.o ./Dsp/Src/FilteringFunctions/arm_fir_lattice_f32.su ./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_f32.d ./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_f32.o ./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_f32.su ./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q15.d ./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q15.o ./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q15.su ./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q31.d ./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q31.o ./Dsp/Src/FilteringFunctions/arm_fir_lattice_init_q31.su ./Dsp/Src/FilteringFunctions/arm_fir_lattice_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_lattice_q15.d ./Dsp/Src/FilteringFunctions/arm_fir_lattice_q15.o ./Dsp/Src/FilteringFunctions/arm_fir_lattice_q15.su ./Dsp/Src/FilteringFunctions/arm_fir_lattice_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_lattice_q31.d ./Dsp/Src/FilteringFunctions/arm_fir_lattice_q31.o ./Dsp/Src/FilteringFunctions/arm_fir_lattice_q31.su ./Dsp/Src/FilteringFunctions/arm_fir_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_q15.d ./Dsp/Src/FilteringFunctions/arm_fir_q15.o ./Dsp/Src/FilteringFunctions/arm_fir_q15.su ./Dsp/Src/FilteringFunctions/arm_fir_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_q31.d ./Dsp/Src/FilteringFunctions/arm_fir_q31.o ./Dsp/Src/FilteringFunctions/arm_fir_q31.su ./Dsp/Src/FilteringFunctions/arm_fir_q7.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_q7.d ./Dsp/Src/FilteringFunctions/arm_fir_q7.o ./Dsp/Src/FilteringFunctions/arm_fir_q7.su ./Dsp/Src/FilteringFunctions/arm_fir_sparse_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_sparse_f32.d ./Dsp/Src/FilteringFunctions/arm_fir_sparse_f32.o ./Dsp/Src/FilteringFunctions/arm_fir_sparse_f32.su ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_f32.d ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_f32.o ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_f32.su ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q15.d ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q15.o ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q15.su ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q31.d ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q31.o ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q31.su ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q7.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q7.d ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q7.o ./Dsp/Src/FilteringFunctions/arm_fir_sparse_init_q7.su ./Dsp/Src/FilteringFunctions/arm_fir_sparse_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_sparse_q15.d ./Dsp/Src/FilteringFunctions/arm_fir_sparse_q15.o ./Dsp/Src/FilteringFunctions/arm_fir_sparse_q15.su ./Dsp/Src/FilteringFunctions/arm_fir_sparse_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_sparse_q31.d ./Dsp/Src/FilteringFunctions/arm_fir_sparse_q31.o ./Dsp/Src/FilteringFunctions/arm_fir_sparse_q31.su ./Dsp/Src/FilteringFunctions/arm_fir_sparse_q7.cyclo ./Dsp/Src/FilteringFunctions/arm_fir_sparse_q7.d ./Dsp/Src/FilteringFunctions/arm_fir_sparse_q7.o ./Dsp/Src/FilteringFunctions/arm_fir_sparse_q7.su
	-$(RM) ./Dsp/Src/FilteringFunctions/arm_iir_lattice_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_iir_lattice_f32.d ./Dsp/Src/FilteringFunctions/arm_iir_lattice_f32.o ./Dsp/Src/FilteringFunctions/arm_iir_lattice_f32.su ./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_f32.d ./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_f32.o ./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_f32.su ./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q15.d ./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q15.o ./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q15.su ./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q31.d ./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q31.o ./Dsp/Src/FilteringFunctions/arm_iir_lattice_init_q31.su ./Dsp/Src/FilteringFunctions/arm_iir_lattice_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_iir_lattice_q15.d ./Dsp/Src/FilteringFunctions/arm_iir_lattice_q15.o ./Dsp/Src/FilteringFunctions/arm_iir_lattice_q15.su ./Dsp/Src/FilteringFunctions/arm_iir_lattice_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_iir_lattice_q31.d ./Dsp/Src/FilteringFunctions/arm_iir_lattice_q31.o ./Dsp/Src/FilteringFunctions/arm_iir_lattice_q31.su ./Dsp/Src/FilteringFunctions/arm_lms_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_lms_f32.d ./Dsp/Src/FilteringFunctions/arm_lms_f32.o ./Dsp/Src/FilteringFunctions/arm_lms_f32.su ./Dsp/Src/FilteringFunctions/arm_lms_init_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_lms_init_f32.d ./Dsp/Src/FilteringFunctions/arm_lms_init_f32.o ./Dsp/Src/FilteringFunctions/arm_lms_init_f32.su ./Dsp/Src/FilteringFunctions/arm_lms_init_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_lms_init_q15.d ./Dsp/Src/FilteringFunctions/arm_lms_init_q15.o ./Dsp/Src/FilteringFunctions/arm_lms_init_q15.su ./Dsp/Src/FilteringFunctions/arm_lms_init_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_lms_init_q31.d ./Dsp/Src/FilteringFunctions/arm_lms_init_q31.o ./Dsp/Src/FilteringFunctions/arm_lms_init_q31.su ./Dsp/Src/FilteringFunctions/arm_lms_norm_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_lms_norm_f32.d ./Dsp/Src/FilteringFunctions/arm_lms_norm_f32.o ./Dsp/Src/FilteringFunctions/arm_lms_norm_f32.su ./Dsp/Src/FilteringFunctions/arm_lms_norm_init_f32.cyclo ./Dsp/Src/FilteringFunctions/arm_lms_norm_init_f32.d ./Dsp/Src/FilteringFunctions/arm_lms_norm_init_f32.o ./Dsp/Src/FilteringFunctions/arm_lms_norm_init_f32.su ./Dsp/Src/FilteringFunctions/arm_lms_norm_init_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_lms_norm_init_q15.d ./Dsp/Src/FilteringFunctions/arm_lms_norm_init_q15.o ./Dsp/Src/FilteringFunctions/arm_lms_norm_init_q15.su ./Dsp/Src/FilteringFunctions/arm_lms_norm_init_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_lms_norm_init_q31.d ./Dsp/Src/FilteringFunctions/arm_lms_norm_init_q31.o ./Dsp/Src/FilteringFunctions/arm_lms_norm_init_q31.su ./Dsp/Src/FilteringFunctions/arm_lms_norm_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_lms_norm_q15.d ./Dsp/Src/FilteringFunctions/arm_lms_norm_q15.o ./Dsp/Src/FilteringFunctions/arm_lms_norm_q15.su ./Dsp/Src/FilteringFunctions/arm_lms_norm_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_lms_norm_q31.d ./Dsp/Src/FilteringFunctions/arm_lms_norm_q31.o ./Dsp/Src/FilteringFunctions/arm_lms_norm_q31.su ./Dsp/Src/FilteringFunctions/arm_lms_q15.cyclo ./Dsp/Src/FilteringFunctions/arm_lms_q15.d ./Dsp/Src/FilteringFunctions/arm_lms_q15.o ./Dsp/Src/FilteringFunctions/arm_lms_q15.su ./Dsp/Src/FilteringFunctions/arm_lms_q31.cyclo ./Dsp/Src/FilteringFunctions/arm_lms_q31.d ./Dsp/Src/FilteringFunctions/arm_lms_q31.o ./Dsp/Src/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-Dsp-2f-Src-2f-FilteringFunctions

